name: verify
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: check compiling sketch
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
        board: "arduino:avr:uno"
        sketch: ./preybot.ino
